require: rubocop-rspec

Rails:
  Enabled: true
  
AllCops:
  TargetRubyVersion: 2.1
  UseCache: false
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'spec/internal/**/*'
    - 'misc/**/*'
    - 'tmp/**/*'

Lint/UselessAssignment:
  Exclude:
    - 'spec/factories/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'app/models/concerns/geo_works/extractors/iso19139_helper.rb'
    - 'app/helpers/metadata_extraction_helper.rb'
    - 'app/models/concerns/file_set/image_file_behavior.rb'
    - 'app/models/concerns/file_set/raster_file_behavior.rb'
    - 'app/models/concerns/file_set/vector_file_behavior.rb'
    - 'app/models/concerns/georeferenced_behavior.rb'
    - 'app/models/solr_document.rb'
    - 'app/schemas/geo_works/basic_geo_metadata_required.rb'
    - 'app/services/geo_works/discovery/geoblacklight_document.rb'
    - 'config/**/*.rb'
    - 'app/values/geo_works/coverage.rb'
    - 'app/values/geo_works/time_period.rb'
    - 'lib/geo_works/fgdc_metadata_extractor.rb'
    - 'lib/generators/geo_works/install_generator.rb'
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/concerns/geo_works/extractors/iso19139_helper.rb'
    - 'lib/geo_works/fgdc_metadata_extractor.rb'
    - 'app/controllers/concerns/geo_works/file_sets_controller_behavior.rb'

Metrics/MethodLength:
  Max: 14
  Exclude:
    - 'Rakefile'
    - 'app/models/concerns/geo_works/extractors/iso19139_helper.rb'
    - 'app/services/geo_works/file_set_derivatives_service.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'lib/generators/geo_works/install_generator.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/spec_helper.rb'

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/FilePath:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
